language: python
sudo: required
dist: xenial

python:
  - "3.7"
  - "3.6"
  - "3.5"

matrix:
  fast_finish: true

env:
  - RUNCOVERAGE=1 ROBOTPY_NO_DEPS=1

# command to install dependencies
install:
  - pip install -U pip
  - pip install -r travis-requirements.txt
# command to run tests
script:
  - tests/run_tests.sh

deploy:
- provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
    python: "3.6"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fb1c026e64fdd70d27b
    on_success: change
    on_failure: always
    on_start: never
